### ISSUE TITLE
Create toggle for nightly shutdown of an environment

### ISSUE THREAD

**Issue by daviestim** [gbolo/aws-power-toggle#19]
It'd be great if there was a toggle slider that determined whether an environment was going to be shutdown automatically at a globally configured time. This would enable a user to make an environment eligible for nightly shutdown or not based on the usage pattern of the environment.

**Comment by gbolo** [comment]
hi @daviestim 

Currently, the backend holds no permanent state (it only holds an environment cache to minimise API calls to aws). The web UI is simple and currently only interacts with the backend API to display and start/stop environments. It was not designed to apply any permanent configuration to the backend. In order to accomplish this, considerable amount of redesigning needs to take place.

Perhaps it would be simpler to put this logic somewhere else (like a script with a cronjob) and have that script use the simplified `aws-power-toggle` API to toggle the nightly shutdown. Another option would be to extend the backend to support a shutdown timer, however, without permanent state, this information would be wiped on restart.
